.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. livecoin_qt test_livecoin_qt
clean: FORCE
	$(MAKE) -C .. livecoin_qt_clean test_livecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_livecoin_qt_check
livecoin-qt livecoin-qt.exe: FORCE
	 $(MAKE) -C .. livecoin_qt
